### ISSUE TITLE
Synchronize IP with Keep Alive

### ISSUE THREAD

**Issue by hpossn** [hedwig-project/Morpheus#6]
Morpheus should send Keep Alive Messages to the cloud, at a certain rate, where the cloud can get its updated IP address

**Comment by hugopossani** [comment]
> The daemon process should detect changes in IP address and send a message through MQTT, in the system topic.
> 
> This IP polling should use two different approaches:
> 
> In case of a linux like system, inotify service should be used
> In case of a windows machine, or if inotify is not available, query the IP from a service (as http://icanhazip.com/) timely in an established interval to notice any changes.
